server:
  name: "project-api"
  addr: "127.0.0.1:80"
zap:
  debugFileName: "..\\logs\\project-api\\debug\\project-debug.log"
  infoFileName:  "..\\logs\\project-api\\info\\project-info.log"
  warnFileName:  "..\\logs\\project-api\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
etcd:
  addrs:
    - "127.0.0.1:2379"