version: '3'
services:
  redis:
    image: redis
    container_name: my-redis
    environment:
      - REDIS_PASSWORD=""
      - REDIS_APPENDONLY=yes
      - REDIS_MAXMEMORY=100mb
    volumes:
      - /app/redis/data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped